version: '3'

services:
  registry:
    image: registry:2
    ports:
      - 127.0.0.1:5000:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./volumes/data:/data

  nginx:
    build: containers/nginx
    ports:
      - 5043:443
    links:
      - registry:registry
    volumes:
      - ./keys/authentication:/etc/nginx/auth
      - ./keys/certs:/etc/nginx/certs